package com.magicval.model.card;

import java.io.IOException;

import com.magicval.model.image.GathererCardImageLoader;

import android.graphics.Bitmap;
import android.os.Parcel;
import android.os.Parcelable;

/**
 * A Card is, for the purposes of this application, a tradable object.
 * It has a name and a price to distinguish itself.
 * Cards are also Parcelable for the purposes of sending them
 * between Activity instances.
 * @author Paul Gibler
 *
 */
public class Card implements Parcelable {
	/**
	 * A URL friendly version of the name of this Card.
	 */
	private String nameForURL = null;
	/**
	 * Returns a URL friendly version of the name of this Card.
	 * @return A URL friendly version of the name of this Card.
	 */
	public String getNameForURL() {
		if(nameForURL == null)
		{
			nameForURL = name.replace(" ", "%20");
		}
		return nameForURL;
	}
	/**
	 * The name returned from searching for this Card.
	 */
	private String name;
	/**
	 * Returns the name returned from searching for this Card.
	 * This string is the one found during
	 * the price search of the card.
	 * @return The found name of the card.
	 */
	public String getNameFromSearch() {
		return name;
	}
	/**
	 * The monetary value of the card.
	 */
	private MonetaryValue monetaryValue;
	/**
	 * Returns the monetary value of this card.
	 * @return The monetary value of this card.
	 */
	public MonetaryValue getMonetaryValue()
	{
		return monetaryValue;
	}
	
	/**
	 * Stores the image of the Card;
	 */
	private Bitmap image = null;
	/**
	 * Loads this Card's image. Lazily loads the Card image.
	 * @return A Bitmap image of the Card.
	 * @throws IOException If the image fails to load, throw this exception.
	 */
	public Bitmap getImage() throws IOException {
		if(image == null)
		{
			image = new GathererCardImageLoader().getImage(this);
		}
		return image;
	}
	
	/**
	 * Creates an instance of Card.
	 * @param name The name of the card.
	 * @param current The current price of the card.
	 * @param high The highest price the card has been.
	 * @param low The lowest price the card has been.
	 */
	public Card(final String name, final String current, final String high, final String low)
	{
		init(name, new MonetaryValue(current, high, low));
	}

	/**
	 * Creates an instance of Card.
	 * @param name The name of the Card.
	 * @param name The actual string that was the Card name.
	 * @param value The MonetaryValue of the Card. Contains current price, highest price, and lowest price.
	 */
	public Card(final String name, MonetaryValue value)
	{
		init(name, value);
	}
	
	/**
	 * Creates an instance of Card with no MonetaryValue.
	 * @param name The name of the Card.
	 * @param name The actual string that was the Card name.
	 */
	public Card(final String name)
	{
		init(name, null);
	}

	/**
	 * Creates an instance of Card from a Parcel.
	 * @param p The Parcel to create this Card from.
	 */
	public Card(Parcel p)
	{
		readFromParcel(p);
	}
	
	// Parcelable methods
	public void writeToParcel(Parcel dest, int flags) {
		dest.writeString(name);
		dest.writeDouble(monetaryValue.getCurrentPrice());
		dest.writeDouble(monetaryValue.getHighPrice());
		dest.writeDouble(monetaryValue.getLowPrice());
		dest.writeParcelable(image, 0);	
	}
	
    public int describeContents() {
        return 0;
    }
	
	public static final Parcelable.Creator<Card> CREATOR
    = new Parcelable.Creator<Card>() {
		public Card createFromParcel(Parcel in) {
		    return new Card(in);
		}
		
		public Card[] newArray(int size) {
		    return new Card[size];
		}
	};
		
	// Private methods
	
	/**
	 * Reads in this Card from a Parcel.
	 */
	private void readFromParcel(Parcel p)
	{
		name = p.readString();	// Name From Search
		monetaryValue = new MonetaryValue(
				p.readDouble(),				// Current
				p.readDouble(),				// High
				p.readDouble());			// Low
		image = p.readParcelable(null);
	}
	
	/**
	 * Standard initializer for Card.
	 * @param name The name of the Card as generated by the search.
	 * @param monetaryValue The value of the Card.
	 */
	private void init(final String name, MonetaryValue monetaryValue) {
		this.name = name;
		this.monetaryValue = monetaryValue;
	}
}
